### ISSUE TITLE
Contribuciones 3.3

### ISSUE THREAD

**Issue by eclipxe13** [orlandocharles/cfdi#2]
Hola, estoy revisando y entendiendo tu proyecto, me parece interesante y me gustaría colaborar con él.

Me surgen algunas dudas:
- Tienes un canal abierto para platicar? Se me ocurre que gitter puede ser de ayuda.
- Usas Semantic Versioning? Es de especial utilidad dado que tienes tu librería en packagist y los que podríamos usarla nos interesa no introducir cambios inesperados.
- Tienes pensado implementar algún estándar de estilo de código código? PSR-2 por ejemplo con phpcs y php-cs-fixer es muy fácil de usar.
- Tienes algún avance en los test? En lo personal podría comenzar con contribuciones de este tipo sobre phpunit.
- Hay alguna razón para soportar PHP 5.6? Trabajar con PHP 7.0 tiene muchas ventajas como el uso de tipo de datos.

En fin, me gustaría poder platicar contigo para solucionar estas dudas básicas, entender bien cómo planeas llevar tu proyecto y poder contribuir.

**Comment by orlandocharles** [comment]
Hola Carlos,

Sobre tus dudas:

* No tengo ningún canal abierto para el proyecto pero le di un vistazo a gitter y me agrada la idea de poder utilizar la plataforma para el proyecto.
* Sobre Semantic Versioning y Coding Style, la respuesta es si, se pretende utilizar PSR-2. No eh tenido el tiempo de subir el archivo CONTRIBUTING.md donde vendrá detallado estos dos puntos.
* Hay una rama de tests que pretendo juntar con master pero tampoco he tenido el tiempo de meterle mano, siéntete libre de contribuir.
* La razón era que estaba haciendo pruebas en un servidor que no soporta 7.0 pero pretendo cambiar la versión a 7.0 antes de liberar el proyecto.

Me puedes contactar mediante el correo que tengo en mi cuenta de Github mientras hago un canal en gitter.

**Comment by aramirez92** [comment]
Me quiero unir @orlandocharles @eclipxe13

**Comment by orlandocharles** [comment]
@aramirez92 hay un canal en [Gitter](https://gitter.im/orlandocharles/cfdi) donde podemos hablar del tema.
